In [18]:
# Load Libraries
import os
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense
import numpy as np

# Functions for each model

In [20]:
# Model 1: Classification
def model1(selFeatures):
 
    # Load the models
    model1 = load_model("model/best_clf.sav") 
        
    prediction1 = model1.predict_classes(selFeatures)
    print(prediction1)

    return jsonify(prediction1)

# Model 2: Deep Learning
def model2(selFeatures):
 
    Feature_list=[int(i) for i in selFeatures]

    test=np.array(Feature_list, dtype=np.int32).reshape(1,-1)

    # Load the models
    model2 = load_model("model/best_dl.h5") 
        
    prediction2 = model2.predict_classes(test)
    print(prediction2)

    return prediction2

# Model 3: Random Forest
def model3(selFeatures):
 
    # Load the models
    model3 = load_model("model/best_rf.sav") 
        
    prediction3 = model3.predict_classes(selFeatures)
    print(prediction3)

    return jsonify(prediction3)

def model4(selFeatures):
 
    # Load the models
    model4 = load_model("model/best_knn.sav") 
        
    prediction4 = model4.predict_classes(selFeatures)
    print(prediction4)

    return jsonify(prediction4)

In [56]:
myFeatures = [1,0,0,0,1,0,0,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0]

test=np.array(myFeatures, dtype=np.int32).reshape(1,-1)

result = model2(test)
test

[3]


array([[1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0]])

In [62]:
selFeatures = ('10001001111000010000100')
Feature_list=[int(i) for i in selFeatures]

test=np.array(Feature_list, dtype=np.int32).reshape(1,-1)
test

array([[1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0]])

In [63]:
model2(test)

[3]


array([3], dtype=int64)

In [64]:
selFeatures = ('10001001000000010000100')

In [65]:
model2(selFeatures)

ValueError: Error when checking input: expected dense_input to have 2 dimensions, but got array with shape ()